In [1]:
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score

In [2]:
heart_df=pd.read_csv("heart.csv")

In [3]:
heart_df.columns
heart_df.info()
heart_df["target"].nunique()
heart_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [4]:
X=heart_df.drop("target",axis=1)
y=heart_df["target"]

In [5]:
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [6]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [7]:
# Train Test Split

X_train, X_test, y_train, y_test = train_test_split(
    X,y, test_size=0.2, random_state=42
)

In [8]:
y_train[y_train == 1] # 133
y_train[y_train == 0] # 105

202    0
196    0
176    0
177    0
258    0
      ..
257    0
214    0
302    0
188    0
270    0
Name: target, Length: 109, dtype: int64

In [9]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [10]:
y_pred = model.predict(X_test)

In [11]:
print("Accuracy :",accuracy_score(y_test , y_pred)*100,"%")

Accuracy : 88.52459016393442 %

In [12]:
print("Precision :",precision_score(y_test , y_pred)*100,"%")

Precision : 87.87878787878788 %

In [22]:
# Evaluation Metrix
from sklearn.metrics import confusion_matrix , accuracy_score,precision_score,recall_score,f1_score
cm = confusion_matrix(y_test , y_pred)
print(cm)
print("Accuracy Score", accuracy_score(y_test,y_pred))
print("Precision Score", precision_score(y_test,y_pred))
print("Recall Score", recall_score(y_test,y_pred))
print("F1 Score", f1_score(y_test,y_pred))

[[25  4]
 [ 5 27]]
Accuracy Score 0.8524590163934426
Precision Score 0.8709677419354839
Recall Score 0.84375
F1 Score 0.8571428571428571

In [14]:
y_pred

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [15]:
# Scaling 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [16]:
X_train

array([[-1.35679832,  0.72250438,  0.00809909, ...,  0.95390513,
        -0.68970073, -0.50904773],
       [ 0.38508599,  0.72250438, -0.97189094, ...,  0.95390513,
        -0.68970073,  1.17848036],
       [-0.92132724,  0.72250438,  0.98808912, ..., -0.69498803,
        -0.68970073, -0.50904773],
       ...,
       [ 1.58263146,  0.72250438,  1.96807914, ..., -0.69498803,
         0.32186034, -0.50904773],
       [-0.92132724,  0.72250438, -0.97189094, ...,  0.95390513,
        -0.68970073,  1.17848036],
       [ 0.92942484, -1.38407465,  0.00809909, ...,  0.95390513,
         1.33342142, -0.50904773]], shape=(242, 13))

In [ ]:
X_test

In [18]:
model.fit(X_train , y_train)
y_pred = model.predict(X_test)
print("Accuracy :",accuracy_score(y_test , y_pred)*100,"%")
print("Precision :",precision_score(y_test , y_pred)*100,"%")

Accuracy : 85.24590163934425 %
Precision : 87.09677419354838 %

In [25]:
import pandas as pd
from sklearn.metrics import precision_score, accuracy_score, recall_score 
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [27]:
heart_df = pd.read_csv("heart.csv")
heart_df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [28]:
X=heart_df.drop("target",axis=1)
y=heart_df["target"]

In [29]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [31]:
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [32]:
X_train.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
132,42,1,1,120,295,0,1,162,0,0.0,2,0,2
202,58,1,0,150,270,0,0,111,1,0.8,2,0,3
196,46,1,2,150,231,0,1,147,0,3.6,1,0,2
75,55,0,1,135,250,0,0,161,0,1.4,1,0,2
176,60,1,0,117,230,1,1,160,1,1.4,2,2,3

In [33]:
#Naive Bayes
gnb_model=GaussianNB()
gnb_model.fit(X_train,y_train)

GaussianNB()

In [34]:
y_pred = gnb_model.predict(X_test)

In [35]:
# Evaluation 

# X = Questions
# y = Answers

# X_train = Practice Questions
# y_train = Practice Answers

# X_test = Final Exam Questions
# y_test = Final Exam Answers

# y_pred = Predicted values generated by the model.
print("recall score",recall_score(y_test , y_pred))
print("accuracy score",accuracy_score(y_test , y_pred))
print("precision score",precision_score(y_test , y_pred))

recall score 0.84375
accuracy score 0.8688524590163934
precision score 0.9